### ISSUE TITLE
/runs/profile (Run profiler) doesn't work for Lauren

### ISSUE THREAD

**Issue by lrbridge** [muymoo/profile-it#1]
@muymoo I'm all set up to go now and I'll be working on this later tonight.... right now runs/profile doesn't work for me so I can look into that (maybe a permission-y thing)

suggestions on next steps?  idk where you're at exactly

**Comment by muymoo** [comment]
You'll need to run `chmod a+s /use/sbin/dtrace`

Not exactly safe, but it will work. Can you get the runTests method to
actual produce a stack trace in mongodb? It was running and inserting stuff
into the db, but the dtrace stack was empty.

On Saturday, March 21, 2015, lrbridge notifications@github.com wrote:

> @muymoo https://github.com/muymoo I'm all set up to go now and I'll be
> working on this later tonight.... right now runs/profile doesn't work for
> me so I can look into that (maybe a permission-y thing)
> 
> suggestions on next steps? idk where you're at exactly
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/muymoo/profile-it/issues/1.

## 

Matt Momont
University of Notre Dame
The Mating Ritual http://thematingritual.com
mattmomont.com
