### ISSUE TITLE
GET /%7B%7Bresult.flamegraph%7D%7D 404

### ISSUE THREAD

**Issue by lrbridge** [muymoo/profile-it#3]
Progress bar looks great, but I'm getting a 404 for the flamegraph... I saw this before occasionally, it's like the Angular binding with that svg data isn't working all the time.

**Comment by muymoo** [comment]
Yea, it only works on the first load. If you refresh the page, it fails with that error. I've tried unsetting result.flamegraph while a new profiling is going on, but it still tries to fetch a new image.
